import React, { useEffect, useRef, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Avatar, Button, Card, FormField, InlineError, Input, PageContainer, PageHeader, PermissionDenied, Select, Textarea, SkeletonRows } from '@shiftos/ui';
import { useSession } from '../../auth/SessionProvider.js';
import { useDefaultBranchId } from '../../auth/useDefaultBranchId.js';
import { useRpcMutation, useRpcQuery } from '../../lib/useRpc.js';
import { uploadEmployeeAvatar } from '../../lib/avatars.js';
import { AvatarUpload } from '../../components/AvatarUpload.js';
import type { Branch, Employee, EmploymentStatus } from '../../types/domain.js';

const MAX_AVATAR_BYTES = 5 * 1024 * 1024;

/** Optional photo picker for the create flow — storage paths are keyed by employee id (migration 030), which doesn't exist until create_employee succeeds, so the file is held locally and uploaded right after creation. */
function PendingAvatarPicker({
  name,
  previewUrl,
  onSelect,
  onClear
}: {
  name: string;
  previewUrl: string | null;
  onSelect: (file: File) => void;
  onClear: () => void;
}): React.ReactElement {
  const inputRef = useRef<HTMLInputElement>(null);
  const [error, setError] = useState<string | null>(null);

  const handleFile = (file: File): void => {
    if (!file.type.startsWith('image/')) {
      setError('Please choose an image file.');
      return;
    }
    if (file.size > MAX_AVATAR_BYTES) {
      setError('Images must be 5MB or smaller.');
      return;
    }
    setError(null);
    onSelect(file);
  };

  return (
    <div className="flex items-center gap-4">
      <Avatar name={name || '?'} src={previewUrl} size={64} />
      <div className="flex flex-col gap-1">
        <div className="flex gap-2">
          <Button type="button" variant="secondary" size="sm" onClick={() => inputRef.current?.click()}>
            {previewUrl ? 'Replace photo' : 'Add photo'}
          </Button>
          {previewUrl ? (
            <Button type="button" variant="ghost" size="sm" onClick={onClear}>
              Remove
            </Button>
          ) : null}
        </div>
        <p className="text-xs text-neutral-500">Optional. JPG or PNG, up to 5MB.</p>
        {error ? <p className="text-xs text-error-text">{error}</p> : null}
      </div>
      <input
        ref={inputRef}
        type="file"
        accept="image/*"
        className="hidden"
        onChange={(e) => {
          const file = e.target.files?.[0];
          e.target.value = '';
          if (file) handleFile(file);
        }}
      />
    </div>
  );
}

const STATUS_OPTIONS: { value: EmploymentStatus; label: string }[] = [
  { value: 'active', label: 'Active' },
  { value: 'inactive', label: 'Inactive' },
  { value: 'on_leave', label: 'On Leave' },
  { value: 'terminated', label: 'Terminated' }
];

/** WEB-007 — Employee Create/Edit Form (WF-003). */
export default function EmployeeFormPage(): React.ReactElement {
  const { employeeId } = useParams<{ employeeId: string }>();
  const isCreate = !employeeId;
  const navigate = useNavigate();
  const { hasPermission, myContext } = useSession();
  const canCreate = hasPermission('employees.create');
  const canUpdate = hasPermission('employees.update');

  // Non-null only when this caller has exactly one accessible branch (Task
  // 1's shared single-branch concept) — in that case the branch field is
  // hidden entirely and that branch is submitted automatically, same
  // auto-hide idiom as InvitationsPage's InviteMemberForm.
  const singleBranchId = useDefaultBranchId();
  const { data: branches } = useRpcQuery<Branch[]>('list_branches', undefined, { enabled: singleBranchId === null });
  const { data: employee, isLoading } = useRpcQuery<Employee>('get_employee', employeeId ? { employeeId } : undefined, {
    enabled: !isCreate
  });

  const [branchId, setBranchId] = useState('');
  const [employeeNumber, setEmployeeNumber] = useState('');
  // Create flow only: the employee number is server-generated by default
  // (057_generate_employee_number.sql) and shown read-only until the manager
  // explicitly opts in to setting their own.
  const [customizeEmployeeNumber, setCustomizeEmployeeNumber] = useState(false);
  const [firstName, setFirstName] = useState('');
  const [lastName, setLastName] = useState('');
  const [email, setEmail] = useState('');
  const [phone, setPhone] = useState('');
  const [hireDate, setHireDate] = useState('');
  const [employmentStatus, setEmploymentStatus] = useState<EmploymentStatus>('active');
  const [notes, setNotes] = useState('');
  const [avatarUrl, setAvatarUrl] = useState<string | null>(null);
  const [pendingAvatarFile, setPendingAvatarFile] = useState<File | null>(null);
  const [pendingAvatarPreview, setPendingAvatarPreview] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    return () => {
      if (pendingAvatarPreview) URL.revokeObjectURL(pendingAvatarPreview);
    };
  }, [pendingAvatarPreview]);

  useEffect(() => {
    if (employee) {
      setBranchId(employee.branch_id);
      setEmployeeNumber(employee.employee_number);
      setFirstName(employee.first_name);
      setLastName(employee.last_name);
      setEmail(employee.email ?? '');
      setPhone(employee.phone ?? '');
      setHireDate(employee.hire_date.slice(0, 10));
      setEmploymentStatus(employee.employment_status);
      setNotes(employee.notes ?? '');
      setAvatarUrl(employee.avatar_url);
    } else if (isCreate && singleBranchId) {
      setBranchId(singleBranchId);
    }
  }, [employee, isCreate, singleBranchId]);

  const createMutation = useRpcMutation<Employee, Record<string, unknown>>('create_employee', {
    invalidates: ['list_employees']
  });

  const updateMutation = useRpcMutation<Employee, Record<string, unknown>>('update_employee', {
    invalidates: ['list_employees', 'get_employee'],
    onSuccess: () => navigate(`/employees/${employeeId}`, { replace: true }),
    onError: (err) => setError(err.message)
  });

  if ((isCreate && !canCreate) || (!isCreate && !canUpdate)) {
    return (
      <PageContainer>
        <PermissionDenied />
      </PageContainer>
    );
  }

  if (!isCreate && isLoading) {
    return (
      <PageContainer>
        <SkeletonRows rows={5} />
      </PageContainer>
    );
  }

  const handleSubmit = async (event: React.FormEvent): Promise<void> => {
    event.preventDefault();
    const resolvedBranchId = singleBranchId ?? branchId;
    // Employee number is optional on create (server auto-generates when
    // omitted, see 057_generate_employee_number.sql) but still required on
    // edit, where the field always shows an existing, already-set value.
    if (!resolvedBranchId || !firstName.trim() || !lastName.trim() || (isCreate && !hireDate) || (!isCreate && !employeeNumber.trim())) {
      setError('Please fill in all required fields.');
      return;
    }
    setError(null);
    if (isCreate) {
      try {
        const created = await createMutation.mutateAsync({
          branchId: resolvedBranchId,
          employeeNumber: employeeNumber.trim() || undefined,
          firstName: firstName.trim(),
          lastName: lastName.trim(),
          email: email.trim() || undefined,
          phone: phone.trim() || undefined,
          hireDate
        });
        // The employee record is the primary success — a failed photo upload
        // (optional, best-effort) never blocks it or gets reported as a save error.
        if (pendingAvatarFile && myContext) {
          try {
            const path = await uploadEmployeeAvatar(myContext.organizationId, created.id, pendingAvatarFile);
            await updateMutation.mutateAsync({ employeeId: created.id, avatarUrl: path });
          } catch {
            // Photo can be added later from the employee's profile — not fatal.
          }
        }
        navigate(`/employees/${created.id}`, { replace: true });
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Could not create employee.');
      }
    } else {
      updateMutation.mutate({
        employeeId,
        branchId: resolvedBranchId,
        employeeNumber: employeeNumber.trim(),
        firstName: firstName.trim(),
        lastName: lastName.trim(),
        email: email.trim() || undefined,
        phone: phone.trim() || undefined,
        employmentStatus,
        notes: notes.trim() || undefined,
        avatarUrl
      });
    }
  };

  const updateAvatar = (newPath: string | null): void => {
    setAvatarUrl(newPath);
    if (!isCreate && employeeId) {
      updateMutation.mutate({ employeeId, avatarUrl: newPath });
    }
  };

  return (
    <PageContainer>
      <PageHeader title={isCreate ? 'Add Employee' : `Edit ${employee?.first_name ?? ''} ${employee?.last_name ?? ''}`} />
      <Card className="mb-4 max-w-2xl">
        {isCreate ? (
          <PendingAvatarPicker
            name={`${firstName} ${lastName}`}
            previewUrl={pendingAvatarPreview}
            onSelect={(file) => {
              setPendingAvatarFile(file);
              setPendingAvatarPreview((prev) => {
                if (prev) URL.revokeObjectURL(prev);
                return URL.createObjectURL(file);
              });
            }}
            onClear={() => {
              setPendingAvatarFile(null);
              setPendingAvatarPreview((prev) => {
                if (prev) URL.revokeObjectURL(prev);
                return null;
              });
            }}
          />
        ) : (
          <AvatarUpload
            name={`${firstName} ${lastName}`}
            path={avatarUrl}
            onUpload={(file) => uploadEmployeeAvatar(myContext!.organizationId, employeeId!, file)}
            onChange={updateAvatar}
          />
        )}
      </Card>
      <Card className="max-w-2xl">
        <form onSubmit={handleSubmit} className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          {singleBranchId === null ? (
            <FormField label="Branch" htmlFor="branchId" required>
              {(fieldProps) => (
                <Select
                  {...fieldProps}
                  value={branchId}
                  onChange={(e) => setBranchId(e.target.value)}
                  placeholder="Select a branch"
                  options={(branches ?? []).map((b) => ({ value: b.id, label: b.name }))}
                />
              )}
            </FormField>
          ) : null}
          {isCreate ? (
            <FormField
              label="Employee number"
              htmlFor="employeeNumber"
              hint={customizeEmployeeNumber ? undefined : 'Assigned automatically when you save — click Edit to set your own.'}
            >
              {(fieldProps) => (
                <div className="flex items-center gap-2">
                  <Input
                    {...fieldProps}
                    value={employeeNumber}
                    onChange={(e) => setEmployeeNumber(e.target.value)}
                    readOnly={!customizeEmployeeNumber}
                    placeholder={customizeEmployeeNumber ? '' : 'Auto-generated'}
                  />
                  <Button
                    type="button"
                    variant="ghost"
                    size="sm"
                    onClick={() => {
                      if (customizeEmployeeNumber) setEmployeeNumber('');
                      setCustomizeEmployeeNumber((prev) => !prev);
                    }}
                  >
                    {customizeEmployeeNumber ? 'Auto' : 'Edit'}
                  </Button>
                </div>
              )}
            </FormField>
          ) : (
            <FormField label="Employee number" htmlFor="employeeNumber" required>
              {(fieldProps) => <Input {...fieldProps} value={employeeNumber} onChange={(e) => setEmployeeNumber(e.target.value)} />}
            </FormField>
          )}
          <FormField label="First name" htmlFor="firstName" required>
            {(fieldProps) => <Input {...fieldProps} value={firstName} onChange={(e) => setFirstName(e.target.value)} />}
          </FormField>
          <FormField label="Last name" htmlFor="lastName" required>
            {(fieldProps) => <Input {...fieldProps} value={lastName} onChange={(e) => setLastName(e.target.value)} />}
          </FormField>
          <FormField label="Email" htmlFor="email">
            {(fieldProps) => <Input {...fieldProps} type="email" value={email} onChange={(e) => setEmail(e.target.value)} />}
          </FormField>
          <FormField label="Phone" htmlFor="phone">
            {(fieldProps) => <Input {...fieldProps} type="tel" value={phone} onChange={(e) => setPhone(e.target.value)} />}
          </FormField>
          {isCreate ? (
            <FormField label="Hire date" htmlFor="hireDate" required>
              {(fieldProps) => <Input {...fieldProps} type="date" value={hireDate} onChange={(e) => setHireDate(e.target.value)} />}
            </FormField>
          ) : (
            <FormField label="Employment status" htmlFor="employmentStatus" required>
              {(fieldProps) => (
                <Select
                  {...fieldProps}
                  value={employmentStatus}
                  onChange={(e) => setEmploymentStatus(e.target.value as EmploymentStatus)}
                  options={STATUS_OPTIONS}
                />
              )}
            </FormField>
          )}
          {!isCreate ? (
            <div className="sm:col-span-2">
              <FormField label="Notes" htmlFor="notes">
                {(fieldProps) => <Textarea {...fieldProps} value={notes} onChange={(e) => setNotes(e.target.value)} />}
              </FormField>
            </div>
          ) : null}
          {error ? (
            <div className="sm:col-span-2">
              <InlineError message={error} />
            </div>
          ) : null}
          <div className="flex items-center gap-3 sm:col-span-2">
            <Button type="submit" loading={createMutation.isPending || updateMutation.isPending}>
              {isCreate ? 'Add employee' : 'Save changes'}
            </Button>
            <Button type="button" variant="secondary" onClick={() => navigate(-1)}>
              Cancel
            </Button>
          </div>
        </form>
      </Card>
    </PageContainer>
  );
}
