-- 057_generate_employee_number.sql
-- Migration: Task 6 (docs/superpowers/specs/2026-09-03-onboarding-ux-audit-design.md
-- §2 Phase 10) -- "Employee creation cleanup". Managers currently must type an
-- `employee_number` by hand on every Add Employee submission even though
-- nothing about it is meaningful to them -- it exists purely so
-- (organization_id, employee_number) has a stable per-tenant identifier
-- (003_create_employees.sql's uq_employees_org_employee_number). This
-- migration makes the column server-generated by default so the frontend can
-- stop requiring manual entry (EmployeeFormPage.tsx), while still allowing an
-- explicit value to be supplied (either at create time via the form's
-- "customize" escape hatch, or later via update_employee) exactly as before.
--
-- Live-data check performed before choosing a format (see Task 6 report):
-- the only two employees in the live project (etodmfsmvhewihboxcrp) are both
-- in the "ShiftOS Test Org" fixture (98fdbe03-36f6-4195-841a-4a882164723a):
-- 'EMP-0001' and 'EMP-002'. Both already match `^EMP-\d+$`; there is no
-- conflicting scheme to work around, and no other organization exists yet to
-- collide with. Format chosen: 'EMP-' || zero-padded sequence, 4 digits
-- minimum ('EMP-0001', 'EMP-0002', ... 'EMP-10000' once five digits are
-- needed) -- scoped per organization_id, matching the existing unique
-- constraint's own scope.
--
-- Existing non-conforming values (e.g. a future manually-entered
-- 'STAFF-7') are never rewritten -- generate_next_employee_number() only
-- computes a number for a *new* row that arrives with no employee_number;
-- it has no trigger or code path that touches any existing row.

-- Computes the next unused 'EMP-####' value for one organization.
-- Concurrency: two simultaneous inserts for the same organization could
-- otherwise both observe the same MAX(...) and race to insert the same
-- candidate (the unique constraint would then reject the loser rather than
-- retry it). An advisory lock keyed on the organization id serializes number
-- generation across concurrent transactions for that organization only --
-- inserts for different organizations never block each other. The lock is
-- transaction-scoped (pg_advisory_xact_lock) so it releases automatically at
-- COMMIT/ROLLBACK, same lifetime as the INSERT itself.
CREATE OR REPLACE FUNCTION public.generate_next_employee_number(p_organization_id uuid)
RETURNS text
LANGUAGE plpgsql
AS $$
DECLARE
  v_next integer;
  v_candidate text;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtext('employees_employee_number'), hashtext(p_organization_id::text));

  -- Reads the numeric part of every existing 'EMP-<digits>' value for this
  -- organization regardless of its padding width (so a pre-existing
  -- 'EMP-002' is read as 2, not ignored) and continues one past the
  -- largest -- existing rows are only ever read here, never rewritten.
  SELECT COALESCE(MAX((substring(employee_number FROM '^EMP-(\d+)$'))::integer), 0) + 1
    INTO v_next
  FROM public.employees
  WHERE organization_id = p_organization_id
    AND employee_number ~ '^EMP-\d+$';

  -- Defends against a gap being manually filled (e.g. someone hand-entered
  -- 'EMP-0005' out of sequence) between the MAX() above and this candidate
  -- being inserted by the caller -- skips forward past any value that
  -- already exists rather than relying solely on the unique constraint to
  -- reject a collision.
  LOOP
    v_candidate := 'EMP-' || lpad(v_next::text, 4, '0');
    EXIT WHEN NOT EXISTS (
      SELECT 1 FROM public.employees
      WHERE organization_id = p_organization_id AND employee_number = v_candidate
    );
    v_next := v_next + 1;
  END LOOP;

  RETURN v_candidate;
END;
$$;

COMMENT ON FUNCTION public.generate_next_employee_number(uuid) IS
  'Returns the next unused ''EMP-####'' employee_number for the given organization (sequence scoped per organization_id, matching uq_employees_org_employee_number). Reads existing ''EMP-<digits>'' values of any padding width to find the current maximum; never modifies existing rows. Serializes concurrent callers for the same organization via a transaction-scoped advisory lock. Internal helper for trg_employees_generate_employee_number -- not exposed as an RPC.';

-- BEFORE INSERT trigger: fills employee_number only when the inserting row
-- did not supply one (NULL, or blank after trimming) -- an explicit value
-- (from update_employee later, from EmployeeFormPage's "customize" escape
-- hatch, or from existing integration tests that already pass their own
-- employeeNumber) always passes through untouched.
CREATE OR REPLACE FUNCTION public.trg_employees_generate_employee_number()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.employee_number IS NULL OR trim(NEW.employee_number) = '' THEN
    NEW.employee_number := public.generate_next_employee_number(NEW.organization_id);
  END IF;
  RETURN NEW;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger t JOIN pg_class c ON t.tgrelid = c.oid
    WHERE t.tgname = 'trg_employees_generate_employee_number' AND c.relname = 'employees')
  THEN
    CREATE TRIGGER trg_employees_generate_employee_number
      BEFORE INSERT ON public.employees
      FOR EACH ROW EXECUTE FUNCTION public.trg_employees_generate_employee_number();
  END IF;
END$$;
